aws:
- account_id: '748560276420'
  account_name: Avichay
  regions:
  - us-east-1
  type: account
github_branch_protection:
  organization:
    amount_of_required_reviews: 4
    required_status_checks: []
