applications:
- api_domain: api.staging.jit.io
  application_name: a
  authentication_mode: selenium
  exclude_paths: []
  login_page_url: https://platform.staging.jit.io/login
  password: encrypted$AQICAHiuvpvALuSdLnnTj5z4D+XYysHZmbLQ2xWihXPmivthFAH82rPCuvtZSglcs9LE8wwZAAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMo3Gb9tHPDMp4k2PtAgEQgCXXcFrflS1I0Usc0vA43If3CQpfhDFbF8tTpe/xr01nm5zwyj5t
  password_css_selector: '[data-test-id=input-password]'
  target_url: https://meshi-bucket.s3.amazonaws.com/openapi.json
  type: api
  username: ohav+testuserdev@jit.io
  username_css_selector: '[data-test-id=input-email]'
- api_domain: api.staging.jit.io
  application_name: https://platform.staging.jit.io
  authentication_mode: selenium
  exclude_paths:
  - https://platform.staging.com/logout
  - ' https://api.staging.jit.io/tenant/delete'
  login_page_url: https://platform.staging.jit.io/login
  password: encrypted$AQICAHiuvpvALuSdLnnTj5z4D+XYysHZmbLQ2xWihXPmivthFAF0nx7PAsIdCWkL0WCP+osEAAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQManP7fDNVf7RvNcYNAgEQgCWmCTDMPJ2ZhrzwLh9aH6PzCHEYcZBwkrNt7amy2y731qcF67ei
  password_css_selector: '[data-test-id=input-password]'
  target_url: https://platform.staging.jit.io
  type: web
  username: ohav+testuserdev@jit.io
  username_css_selector: '[data-test-id=input-email]'
aws:
- account_id: '748560276420'
  account_name: Avichay
  regions:
  - us-east-1
  type: account
github_branch_protection:
  organization:
    amount_of_required_reviews: 4
    required_status_checks: []
