applications:
- application_name: aaa
  authentication_mode: non-authenticated
  exclude_paths:
  - https://platform.staging.com/logout
  - ' https://api.staging.jit.io/tenant/delete'
  target_url: https://platform.staging.jit.io
  type: web
aws:
- account_id: '748560276420'
  account_name: Avichay
  regions:
  - us-east-1
  type: account
github_branch_protection:
  organization:
    amount_of_required_reviews: 4
    required_status_checks: []
