applications:
- application_name: aaaa
  authentication_mode: selenium
  exclude_paths: []
  login_page_url: https://platform.staging.jit.io/login
  password: encrypted$AQICAHiuvpvALuSdLnnTj5z4D+XYysHZmbLQ2xWihXPmivthFAGRqmYcVrk1a4ucd3z2RawQAAAFJzCCBSMGCSqGSIb3DQEHBqCCBRQwggUQAgEAMIIFCQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxuPOo1NJxByia9RHkCARCAggTatbUxrW/LegywY3qu5aAkyzLb9Ptq+DeUSdxnslPIwfVzPp4I6fw+AAftHTi39pZ3mSnU2S11rnA+LmETW/gUMhMEIiOo1gCa9NW1yFYVpKYqUmZqTSsGpNuXbCrfb8Ro42dX9973TS2Wv5m4aRbuvujNMBH/ac1SI9xsKN+9kK16yaaRCVyOcYzNRG2x7VYm2TQqSxxqF/9GKUNvOCKCaUFtEMe0K9NkUUAI8FdISoc5BYHNEqzXoxm1t7Nt2IIlh9nAFJAfOXNy3GtMI9g8kOwlEApDQ+HDh/sX7Cyu4BvI2j2ZjR3NzmXgp2M3z9a3sWEcHZk4X1zn7KcDKY9RYiZahr6YINAj5LvYZEJ4Gac0/WgpE48mlK9rdZLOUtD5/hriX/9Sr9kqFoBbuJXoIQv97Qd56FiB668olHxhGTuCJwhQszjXI/7BDs6Q2eQ6scCEG2DkERvPymUaQ1EiBtsGlEIUsLzWUsav8hAHZM3jgZxaC05n/xyjCodNZX1sx0Ax/Qx/G4de4FK+iBDbU29q3ZtdlbO/6SSp1rX6gkdmLAp33FVgmnUFHriPuNIhC06byGuvQbkQOFJQiNnoeNTtuitOXAJlfcRRBV0PLFlQYhy7DFyyMepKBPt+5iULzHgLycVxxAGIet0SAIu9DNkMa4VBvy4O7ujyNrEX57rGPEnukXTf3Bin214ehiVHVTyyiWgJyIgoxejg4kqgEoYGHulMmA5iCJdfkcuTrEKCboWlHUVJPmfL/pg7MZ8uGTtCKXlXP1JnG3gIgbPO5NIlP8r3ubU1p3AhyjZzVcSWfpEPsiJfq+EoOBuwiCtPsbeLKc04+lCAXuD+xIYSym/Bj9OcXpgztzA7uEvdt0sT5j86rcxIRghA5/0aThPRzpkh2xSQYxvFsOZWEIiFsav/Xe5mXaEOFeo0hugWoZn+olcNMzEZrre3VbAGpLSnqa34oLvdND+h3SFFK7ckBqFQd53th90DEhQxdmfk5QhUFvOfkPt64dsQOtAlVjaGxAWCDhtOPIVJD8c2ehcwDTMvU6Nj7zm8zUiO8B8m6e+W48x1cZH6HBUyXmNnbZ/fdxPIdxu/QOAv1rl1tgtbJyNTtZLXD+OYKpI8CdBwgHohVSEqbnfCv3WpOPLpYLRYGLf5bmZJ6Qeb5YJO5NiJEqNgw85NmRHbyW2Do7dlqwmY//JKp0dZkHfMhEnQT7Lmc5pqh/vJ0tGRJMBLHAXwR26zmDu/WMdHdVf/DKJW3UEiR7xwCPyLqxxhcl4ny3MKGWU7IeMJ8Cryev9aPPvaXHVzQg87szT/hwANX9ydGycuvTpO+HPOpZyDZ3IkfwjXqyfgwjrPi5VRwVpgUBNnfxSNVznG1Vx/BVOLJmQjcBWMY2IGvg+i64Y2a5qhAmV5nuQ6muhTU9aMMNC53S4iSEOrEXrg3inj5Dm0HiKK9OPeE1k89/jqNJt4rx0M+9Bh7NB0l3yqlW+WOb8fQdGkyzjMwayTMyLa43z1Ua5hTD6SuZxswta7enURa/hoSi14T0j76z/9wiOp8ytE9KL/Ux1bA1afXSJFeqFFvO3Z8L5J05e4l5OafcrsNlavaJBQAw/VZLPJ/zKbd8PXAElRo5ZAuiRcxzfVU0+t+iSv23vAd0EwZBOCEMPA
  password_css_selector: '[data-test-id=input-password]'
  target_url: https://meshi-bucket.s3.amazonaws.com/openapi.json
  type: api
  username: avichay@jit.io
  username_css_selector: '[data-test-id=input-email]'
aws:
- account_id: '748560276420'
  account_name: Avichay
  regions:
  - us-east-1
  type: account
github_branch_protection:
  organization:
    amount_of_required_reviews: 4
    required_status_checks: []
