applications:
- api_domain: api.staging.jit.io
  application_name: a
  authentication_mode: selenium
  exclude_paths: []
  login_page_url: https://platform.staging.jit.io/login
  password: encrypted$AQICAHiuvpvALuSdLnnTj5z4D+XYysHZmbLQ2xWihXPmivthFAFWJk30qM2NFwS3GfhGoxm/AAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMH42wziMEUGF1iZTHAgEQgCWHnVrUEwuzOP9zrjwSC0HyNEotJrt6hky0uCFJqU2/nokYd3bi
  password_css_selector: '[data-test-id=input-password]'
  target_url: https://meshi-bucket.s3.amazonaws.com/openapi.json
  type: api
  username: ohav+testuserdev@jit.io
  username_css_selector: '[data-test-id=input-email]'
- api_domain: api.staging.jit.io
  application_name: https://platform.staging.jit.io
  auth_header_name: Authorization
  auth_header_value: encrypted$AQICAHiuvpvALuSdLnnTj5z4D+XYysHZmbLQ2xWihXPmivthFAHZRXr8MV4dRB3sdEV4SQVyAAAFBTCCBQEGCSqGSIb3DQEHBqCCBPIwggTuAgEAMIIE5wYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxMQq36Mq8woIKuaMoCARCAggS4uRn77uXb4f5lincVTiwZpz80VY/wHXtkLQaUs1TeW7rn+8gNbh/n5MV7qB7xIDLglQ6YGQw+8QLvF6MBGs8E9a3uHy79TLMCK6oJSvtEUaSwNgxrE293sqC7JYQCkGfH2co8xMHrgOPFSe3V9VZz+wCN2qT8kLpE0j0hmvZoj0AaXeTUFxQEpi7wjW1k4GFUsqnVMkPf4p/L6i2eXcpaTeWCdHcPX2BHOF3D3/GBC0aA02dsLInIsqQHPf9lRqxQDDHoMtMpcFI7xuaxZ6dWNarJ5l4U2gjdZa0Dd6+EeXKRajN7IP/Ot/shw+aJsmbuZCI44sYr33EAzmDkSeW5HgE8psiYr6qQCwDWKqWL4+8vaeifN74EnFvEbQZJoXyVuqpLIjSehVlVUPu5nROCxsOzePGvxH/j5v90OjDbERCnnHw2NaykVd4hfVgLf1L6WbdSzmjIN3T/8eQGpoB2Y8q2cv41l7obOeZ/2F4OEA5WGF85dTytnNm3aU+DmynR7yxcXKfDYSR/mdq0ZClON5JcJA6rSB2DvR8g5BNIPSwy1XUx62R+qQNUiX3vkprvr9aACGtV2I00hjoJA9HYdZYJXmP4QEfCWVTICRDPT4eZ0DD/cpca7yiKikXhu3GYze/WZLi+wyL7fJc5c5LnzR9w5kceSQV0hAr+WNd2McH0PxadFzLtBzCzcnVckznbIhdgsjho0RuC8mQ75GEZwlXFiMVapDTbj5TI++bJedvffRkiWibG9S9xGH6goYOMrwLmX5itRriaKrGwVYFzTFnxMqYJdeqR0DLdpZsjT9kzAZM0kCybHi6ukxCBhk0Ae21tnwLEgovTMY9z5ut+vPmIwKBQbCC5jpfcUBK4oDPVM2LdVLPhXplyLQQZNYj+Xq98Z2EqufVSt+syVXyScHcVGJgIGq2uay4pKwUjeozgCN4+hiUZRw6OeApXkKMtrVPkI3Q1Y/SQq0L8EgKMfxgal7UAFSF2FWCicVXk4tfeaJqbPM4s+iNUAM6vlqq74SrTGFx9DEHBQELKm4v+My3h8EqEZX2cE4JHuQIWw7T7ZGJyqwwX8cHRPPjEDJceMc6I3McDDOCIQO46BheqSV8eF5x7JZdBQq4ykmNxyZhuW3BklL6xK/1Md+RMyjO1IoC9p3mZbPEd/TzjLp0/XewBEINFylbzHS31nt1qUxI6Qgkty/cOmtr2KsedhEvK7LBGdA/vaJzuXMiDYgUIQBbsgVFtR5ZGgX78x1IXa3bh3x3cXAWOzeDuFJdpOD7hd9oQfO4UCmHJR4sVXlbEi/4qBmO/mMF1S29zQ6S7PSfNdRf/ZfVm9wkpb+XSfYPrlfv5YrxBW5IPyVLDRVcIIU+nTwFhLkc+e9q31/RyKHUfRYmUR3VPoaiJ9P0giBAi0ps9ErKai9eLbAgdn0hKQQSKTj0S6q439zc6nvwSdegx17/Toq2jEYKcwVrfHHVyYjuwF8f+TpXK9Cs30Qa0AP8WmDCatbD56c2wyBkVHau25GI0FsLHeseluT6e6R2OplE/DS1lTUuj25HTnNHyrbe0g/KbK8k8Bdvpma6GdA7u268mpImBcx6LXpDyBvAHAuoUYfxi0Eo=
  authentication_mode: header-bearer
  exclude_paths:
  - https://platform.staging.com/logout
  - ' https://api.staging.jit.io/tenant/delete'
  target_url: https://platform.staging.jit.io
  type: web
aws:
- account_id: '748560276420'
  account_name: Avichay
  regions:
  - us-east-1
  type: account
github_branch_protection:
  organization:
    amount_of_required_reviews: 4
    required_status_checks: []
