a: ${{jit_secrets.secret1}}
applications:
- api_domain: api.staging.jit.io
  application_name: ${{jit_secrets.secret1}}
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://meshi-bucket.s3.amazonaws.com/openapi.json
  type: api
- api_domain: public-firing-range.appspot.com
  application_name: some-name-12
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://public-firing-range.appspot.com
  type: web
aws:
  account_id: '748560276420'
  regions:
  - us-east-1
  type: account
deployment:
  environments:
  - deploy
github_branch_protection:
  organization:
    amount_of_required_reviews: 1
    required_status_checks: []
plan_items:
  item-web-app-scanner:
    staging_env:
      configuration:
      - some-name-12
      tags:
      - deploy
      trigger: deployment
