jobs:
    changed_files:
        runs-on: ubuntu-latest
        name: Test changed-files
        steps:
            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v1.1.3
