aws:
- account_id: '748560276420'
  regions:
  - us-east-1
  type: account
github_branch_protection:
  organization:
    amount_of_required_reviews: 3
    required_status_checks: []
resource_management:  # (tagging/exclude)
  exclude:
    plan-item-slug:
      - name: asset-name-to-exclude 
    Plan-item-slug2:
      - name: asset-name-to-exclude 
        type: aws_acccount

