applications:
- api_domain: juice-shop.herokuapp.com
  application_name: JuiceShop
  authentication_mode: non-authenticated
  exclude_paths: []
  login_page_url: https://platform.staging.jit.io/login
  password_css_selector: ''
  target_url: https://juice-shop.herokuapp.com/
  type: web
- api_domain: api.staging.jit.io
  application_name: AssetServiceAPIStaging
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: .jit/asset-service-staging.json
  type: api
deployment:
  environments:
  - test
github_branch_protection:
  organization:
    amount_of_required_reviews: 1
    required_status_checks: []
plan_items:
  item-web-app-scanner:
    deployment:
      configuration:
      - JuiceShop
      tags:
      - test
      trigger: deployment
