applications: 
  - api_domain: altoromutual.com
    application_name: eli_lily_test4
    authentication_mode: non-authenticated
    exclude_paths: []
    target_url: .jit/eli-lily-test-2.json
    type: api
