applications:
- api_domain: api.myapp.com
  application_name: my app two
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://myapp.com
  type: web
- api_domain: altoromutual.com
  application_name: eli_lily_test
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://altoromutual.com/swagger/properties.json
  type: api
- api_domain: altoromutual.com
  application_name: eli_lily_test4
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: .jit/eli-lily-test-2.json
  type: api
