applications:
- api_domain: api.bandit.jitdev.io
  application_name: jit-bandit-shlomi-test-org
  authentication_key: Authorization
  authentication_mode: header-bearer
  authentication_value: ${{ jit_secrets.web_scan_authentication_value }}
  exclude_paths: []
  target_url: https://platform.bandit.jitdev.io/
  type: web
- api_domain: api.linearb-staging-01.io
  application_name: linear-b--test-api
  authentication_key: Authorization
  authentication_mode: header-bearer
  authentication_value: ${{ jit_secrets.api_scan_authentication_value }}
  exclude_paths: []
  target_url: .jit/linearb.yml
  type: api
deployment:
  environments:
  - nnnnn
github_branch_protection:
  organization:
    amount_of_required_reviews: 1
    required_status_checks: []
plan_items:
  item-build-and-deploy:
    deployment:
      configuration:
      - GuyStagingWeb
      tags:
      - nnnnn
      trigger: deployment
  item-malicious-software-architecture:
    deployment:
      configuration:
      - GuyStagingWeb
      tags:
      - nnnnn
      trigger: deployment
  item-secure-software-development-lifecycle:
    deployment:
      configuration:
      - GuyStagingWeb
      tags:
      - nnnnn
      trigger: deployment
  item-web-app-scanner: {}
