applications:
- api_domain: api.staging.jit.io
  application_name: aaa
  authentication_key: Authorization
  authentication_mode: header-bearer
  authentication_value: ${{ jit_secrets.api_scan_authentication_value }}
  exclude_paths: []
  target_url: https://meshi-bucket.s3.amazonaws.com/openapi.json
  type: api
aws:
- account_id: '748560276420'
  regions:
  - us-east-1
  type: account
github_branch_protection:
  organization:
    amount_of_required_reviews: 3
    required_status_checks: []
resource_management:
  exclude:
    plan_items:
      Plan-item-slug2:
        resources:
        - name: asset-name-to-exclude
          type: aws_account
        - name: asset_slkjalfasljfajslkljkqa
      plan-item-slug:
        resources:
        - name: asset-name-to-exclude
