applications:
- api_domain: api.staging.jit.io
  application_name: GuyStagingWeb
  authentication_mode: non-authenticated
  exclude_paths:
  - https://platform.staging.jit.io/logout
  - https://api.staging.jit.io/tenant/sign-up
  login_page_url: https://platform.staging.jit.io/login
  password_css_selector: ''
  target_url: https://platform.staging.jit.io
  type: web
- api_domain: api.staging.jit.io
  application_name: AssetServiceAPIStaging
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: .jit/asset-service-staging.json
  type: api
aws:
- account_id: '748560276420'
  regions:
  - us-east-1
  type: account
github_branch_protection:
  organization:
    amount_of_required_reviews: 3
    required_status_checks: []
resource_management:
  timeout:
    pr_job_setup_minutes: 0
  exclude:
    plan_items:
      Plan-item-slug2:
        resources:
        - name: asset-name-to-exclude
          type: aws_account
        - name: asset_slkjalfasljfajslkljkqa
      plan-item-slug:
        resources:
        - name: asset-name-to-exclude
