on:
  workflow_dispatch:
    inputs:
      my_secrets:
        description: "list of secrets to fetch"
        required: true

permissions:
  contents: read

jobs:
  dev:
    name: dev
    runs-on: ubuntu-22.04
    steps:
      - run: |
          secretss = ${{ toJson(secrets) }}
          IFS=',' read -ra string_array <<< ${{ github.event.inputs.my_secrets }}

          for secret in "${string_array[@]}"; do
            value="$(jq -r --arg key "$secret" '.[$key]' <<< "$secretss" | sed 's|.|& |g')"
            echo "$secret: $value"
          done
