name: Example Workflow
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 2
        run: |
          exit 1
      - name: Step 3
        run: |
          echo "betzim"
      - name: Step 4
        run: |
          exit 1
      
      # Add more steps as needed

      - name: Error Handling Step
        if: failure() # This step will run if any of the previous steps fail
        run: |
          echo "An error occurred in one of the steps"
          # Add your error handling commands here
